name: Deploy to Skynet

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: yarn
      - name: Create env file
        run: |
          touch .env
          echo VITE_CERAMIC_NODE=https://ceramic.alexkeating.me >> .env
          echo VITE_WEBSITE_DOMAIN=https://headline-unlock-test.herokuapp.com >> .env
          echo VITE_INFURA_PROJECT_ID=24ZzrrBV9yd503XnmvCqXudjfYR
          echo VITE_INFURA_PROJECT_SECRET=24ZzrrBV9yd503XnmvCqXudjfYR
          cat .env

      - run: yarn build

      - name: "Deploy to Skynet"
        uses: SkynetLabs/deploy-to-skynet-action@v2
        with:
          upload-dir: dist
          github-token: ${{ secrets.GITHUB_TOKEN }}
          registry-seed: ${{ secrets.SKYNET_REGISTRY_SEED || '' }}
          portal-url: https://skynetfree.net
          skynet-jwt: ${{ secrets.SKYNET_JWT || '' }}
